from myapp.views.admin.order import *
from myapp.views.admin.finance import *
from myapp.views.admin.thing import *
from myapp.views.admin.classification import *
from myapp.views.admin.tag import *
from myapp.views.admin.user import *
from myapp.views.admin.comment import *
from myapp.views.admin.record import *
from myapp.views.admin.overview import *
from myapp.views.admin.loginLog import *
from myapp.views.admin.opLog import *
from myapp.views.admin.errorLog import *
from myapp.views.admin.banner import *
from myapp.views.admin.ad import *
from myapp.views.admin.notice import *
from myapp.views.admin.ad_cost import *
from myapp.views.admin.store_ad import *
from myapp.views.admin.refund_rank import *
from myapp.views.admin.profit_statement import *
from myapp.views.admin.unsalable_rank import *
